### ISSUE TITLE
[BUG] POST with chunked doesnt work

### ISSUE THREAD

**Issue by LeaYeh** [LeaYeh/webserver#116]
https://github.com/LeaYeh/webserver/blob/827d7f5c384b317a05359eab449fc3c11f84b3d3/source/shell/Request.cpp#L214
@leske42 chunked decoding doesn't work, bc we can not assume in the readbuffer is right equal as 1 chunked data.
Maybe we need a static chunk buffer for waiting the CRLF

_Originally posted by @LeaYeh in https://github.com/LeaYeh/webserver/issues/115#issuecomment-2539993967_

**Comment by leske42** [comment]
So allocating a chunk_size buffer for holding each chunk then reading into it until its full? This feels like something thats sucky to write but i will look into it
